[naver]
title = "SNU 팩트체크 ─ 네이버 뉴스"
url = "https://m.news.naver.com/factcheck/main"
entrySelector = "div.factcheck_list div.factcheck_item._factcheck_item"
titleSelector = "p[class='factcheck_subject_summary']"
linkSelector = "p[class='factcheck_subject_summary'] a"
contentSelector = "div[class^='factcheck_source_rating is']"
waitUntil = "networkidle"
onFail = "stale"

[naver_vaccine]
title = "SNU 팩트체크 ─ 네이버 뉴스 ─ 백신"
url = "https://m.news.naver.com/factcheck/main?section=%EC%BD%94%EB%A1%9C%EB%82%98%EB%B0%B1%EC%8B%A0"
entrySelector = "div.factcheck_list div.factcheck_item._factcheck_item"
titleSelector = "p[class='factcheck_subject_summary']"
linkSelector = "p[class='factcheck_subject_summary'] a"
contentSelector = "div[class^='factcheck_source_rating is']"
waitUntil = "networkidle"
onFail = "stale"

[naver_covid19]
title = "SNU 팩트체크 ─ 네이버 뉴스 ─ 코로나19"
url = "https://m.news.naver.com/factcheck/main?section=%EC%BD%94%EB%A1%9C%EB%82%98+%EB%B0%94%EC%9D%B4%EB%9F%AC%EC%8A%A4"
entrySelector = "div.factcheck_list div.factcheck_item._factcheck_item"
titleSelector = "p[class='factcheck_subject_summary']"
linkSelector = "p[class='factcheck_subject_summary'] a"
contentSelector = "div[class^='factcheck_source_rating is']"
waitUntil = "networkidle"
onFail = "stale"

[notice]
title = "SNU 팩트체크 ─ 공지사항"
url = "http://factcheck.snu.ac.kr/documents?doc_type=notice"
entrySelector = "table.notice_table tbody tr"
titleSelector = "td a"
linkSelector = "td a"
dateSelector = "td:nth-child(2)"
waitUntil = "networkidle"
onFail = "stale"
